# Generated by Django 4.2.2 on 2023-08-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_prediction_diseases_prediction_diseases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
